# Use the official Python base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install the dependencies
# This is a best practice to take advantage of Docker layer caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port your application will run on
EXPOSE 8080

# Define the command to run your application
# The `PORT` variable is automatically provided by Cloud Run,
# so we use that in the run command.
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]
